<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Import</name>
   <tag></tag>
   <elementGuidId>2147ed4f-c44e-4b0d-8aa1-692f2cb07d9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;importexcel&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='importexcel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6c0121a-901e-45d7-a828-f9f5eabc27d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87c88507-667e-4660-aac2-5f9ed53cbef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>importexcel</value>
      <webElementGuid>fca6462c-68ad-4f83-b10b-b82816b1fd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn bg-olive</value>
      <webElementGuid>be5b440f-47cc-469c-b084-15c81e0bdf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>b7a6f052-ba48-484f-9548-9b8e483ede7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#importexcel-window</value>
      <webElementGuid>c6275738-1da3-4077-ad23-1c0cbcae893c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

Import
</value>
      <webElementGuid>3229dfdf-807c-423c-95e0-a8362c7d48d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit108&quot;]/body[@class=&quot;sidebar-mini layout-fixed control-sidebar-slide-open&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/form[1]/div[@class=&quot;content-header clearfix&quot;]/div[@class=&quot;float-right&quot;]/button[@class=&quot;btn bg-olive&quot;]</value>
      <webElementGuid>ddcb5a44-ab89-400d-86f7-f4c332216190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='importexcel']</value>
      <webElementGuid>2e5503fa-f94c-49ec-a553-132ff74931de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print PDF invoices (all found)'])[1]/preceding::button[3]</value>
      <webElementGuid>bb12f47b-6999-43bf-81c9-58b67a13b123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Import']/parent::*</value>
      <webElementGuid>0164cf9b-4005-41e6-9c1b-350159db07a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>c2bf2f01-d109-484a-9ba5-c135d87fe77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'importexcel' and (text() = '

Import
' or . = '

Import
')]</value>
      <webElementGuid>c97d93e0-c791-40ac-a9e6-6d836c2f3de7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
