<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_nextappmail.com</name>
   <tag></tag>
   <elementGuidId>dc875aa2-3777-411c-a42f-a01f675bda87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a2a193d-22d2-4c79-b0b5-b4a11b3cd063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail</value>
      <webElementGuid>57f9b5e4-31dc-42e1-9db3-1a0a47b488d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:nextapp@mail.com</value>
      <webElementGuid>b3c269e5-bd83-465d-a714-4d169bdeba45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nextapp@mail.com</value>
      <webElementGuid>81ecce27-70ff-4c7a-a896-e00cb6e7e4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail&quot;)</value>
      <webElementGuid>ddfba967-4366-41d0-8382-9fa9b0c23309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail']</value>
      <webElementGuid>8b0ac3d5-0d4b-4f55-ab2b-4a6d809fb5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00__0']/td[2]/a</value>
      <webElementGuid>cfbb6d7d-6e08-480c-a7cb-92fb11c6d1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'nextapp@mail.com')]</value>
      <webElementGuid>5652b436-30e7-4c54-adfb-1de8f38a7826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::a[1]</value>
      <webElementGuid>76c6e806-0b47-4c02-9459-2391073701a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W 98568956985'])[1]/following::a[3]</value>
      <webElementGuid>3d0f57fa-3e2a-4856-a330-fcf6cad2194f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address:'])[1]/preceding::a[1]</value>
      <webElementGuid>9791da04-0278-4e8f-97ce-103e363cd0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>b972036e-9acf-446c-9b42-798ede3692fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='nextapp@mail.com']/parent::*</value>
      <webElementGuid>539bec62-f607-487e-a32b-6348d4d11562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:nextapp@mail.com')]</value>
      <webElementGuid>e94f5b3f-8bdd-4c8c-b4bf-8b34bf02c7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>75c9ab61-803a-4658-bae4-329d671752c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_ucEmailBook_dgEmail_ctl00_ctl04_lnkEmail' and @href = 'mailto:nextapp@mail.com' and (text() = 'nextapp@mail.com' or . = 'nextapp@mail.com')]</value>
      <webElementGuid>73abd576-6474-4373-b657-02f691b7c3bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
