<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Striven Website_img-circle</name>
   <tag></tag>
   <elementGuidId>c3f3bde3-4b70-4b6a-8d50-8a4ddfa45360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e27d443a-0afb-4a95-be57-15531ccda57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle</value>
      <webElementGuid>25777ad8-d6f9-4486-a234-9100abde9dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/no_profile_image.png</value>
      <webElementGuid>11a423e0-e217-45e6-919f-1f2d888d1b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture&quot;)/img[@class=&quot;img-circle&quot;]</value>
      <webElementGuid>bdec27fa-830c-40cc-ac1c-c0358b9b0387</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture']/img</value>
      <webElementGuid>5152202c-505e-401c-86db-a0805649d83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>d6e209b3-80e8-4795-8b01-6d91155439e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/no_profile_image.png']</value>
      <webElementGuid>0a9bc163-3460-4930-b1ab-bf9025a8df48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
