<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Add Content_rdWindow</name>
   <tag></tag>
   <elementGuidId>3df4eaa6-1fd8-491e-8925-50e35403ecc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='rdWindow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;rdWindow&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>16a1b515-2d9e-48c8-93d6-c976096b8786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rdWindow</value>
      <webElementGuid>d1f0433e-bcef-474b-ac82-60d84754ef72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Collaboration/Hub/DialogHubContentInfo.aspx?GroupID=1&amp;ParentID=0&amp;ContentID=undefined&amp;sectionID=1&amp;objectID=59&amp;keyID=0&amp;onOpen=undefined&amp;ContentTypeId=1&amp;rwndrnd=0.9264172144782044</value>
      <webElementGuid>253fa844-8274-45a5-b3d0-e7a95469155d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>17ac254a-cf23-4277-9119-7e2cdd272f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_rdWindow_C&quot;)/iframe[1]</value>
      <webElementGuid>e9db2450-9225-40f3-a21e-93fb1470f359</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='rdWindow']</value>
      <webElementGuid>4a00d653-b266-4f57-b846-0be983986eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_rdWindow_C']/iframe</value>
      <webElementGuid>cce275b2-9256-4ba5-a5cb-5bae48363989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>487657bd-4874-4d88-827a-462d7b86d15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'rdWindow' and @src = '/Collaboration/Hub/DialogHubContentInfo.aspx?GroupID=1&amp;ParentID=0&amp;ContentID=undefined&amp;sectionID=1&amp;objectID=59&amp;keyID=0&amp;onOpen=undefined&amp;ContentTypeId=1&amp;rwndrnd=0.9264172144782044']</value>
      <webElementGuid>f8184899-8f06-4ce6-aa6d-f2ef52e0b9b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
