<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hub</name>
   <tag></tag>
   <elementGuidId>8746ab38-86b6-4db5-9067-6f15febddc73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mobile-menu']/ul/li/div/div/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e274e74-a743-483f-878f-cc23ef62795b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Collaboration/Hub/Hub.aspx?nav=1</value>
      <webElementGuid>0e625aa7-ae2a-4a71-a390-687e2c32cecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hub</value>
      <webElementGuid>f5921fdb-3c63-494a-8da4-ec6a5adf3baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile-menu&quot;)/ul[@class=&quot;nav navbar-nav main-menu main-menu-hintview&quot;]/li[@class=&quot;dropdown open&quot;]/div[@class=&quot;dropdown-menu multi-column&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/ul[@class=&quot;multi-column-dropdown&quot;]/li[3]/a[1]</value>
      <webElementGuid>27ae7c33-65c7-4d2d-8923-86084cdf3403</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobile-menu']/ul/li/div/div/div/ul/li[3]/a</value>
      <webElementGuid>ec53d276-0556-45ab-ad65-757b7d777269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hub')]</value>
      <webElementGuid>9225c53d-3f20-4c91-9bb0-9a0b4d0585e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Goals'])[1]/following::a[1]</value>
      <webElementGuid>43e413f3-ed85-4099-a3af-9d60d5f3a80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rocks'])[1]/following::a[2]</value>
      <webElementGuid>10b759b1-2d10-4d6a-a4b9-4d355a74bac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assets'])[1]/preceding::a[1]</value>
      <webElementGuid>101ae262-79d7-47ac-8499-6f79abad012d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List'])[1]/preceding::a[2]</value>
      <webElementGuid>8a41954a-144e-4ba1-a856-6119e31abbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hub']/parent::*</value>
      <webElementGuid>f57efd2b-0bcd-4693-939a-de634c5b7cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Collaboration/Hub/Hub.aspx?nav=1')]</value>
      <webElementGuid>c9ad7416-18bf-47e6-bad4-625f51f2656d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/ul/li[3]/a</value>
      <webElementGuid>8f91ece8-2057-4cf8-91e1-3ad93fb59955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Collaboration/Hub/Hub.aspx?nav=1' and (text() = 'Hub' or . = 'Hub')]</value>
      <webElementGuid>90bd5789-b998-43b7-b190-b4447e254008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
