<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Striven Website_img-circle</name>
   <tag></tag>
   <elementGuidId>3057b37c-bcc5-434b-87db-f5e86922bf87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>24f3eeaa-6dd7-431b-a5cf-18156edad708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle</value>
      <webElementGuid>dabdf251-9789-41ef-a276-ce2abf952a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/no_profile_image.png</value>
      <webElementGuid>7a057ad1-45f0-4cca-a86c-9adf7a4c23a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture&quot;)/img[@class=&quot;img-circle&quot;]</value>
      <webElementGuid>3a37fada-b7c6-42a9-aa63-5365d063c83f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture']/img</value>
      <webElementGuid>20fed3d2-a2b7-497e-b924-cc42737fcb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>72a73d26-52eb-4629-8423-101f04a3facb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/no_profile_image.png']</value>
      <webElementGuid>64b5172f-04f8-4799-a3a6-975335deed6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
