<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_classFrame</name>
   <tag></tag>
   <elementGuidId>39e9c4b5-7f72-4b3e-b02a-fa6de32bc1fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='classFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;classFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5e16ceea-80d4-45c5-bb75-861e88acd676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>overview-summary.html</value>
      <webElementGuid>cd613e76-7234-4bb3-9f98-3fca349a9d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>fd29361b-e52a-4869-b41c-ecb39ad6cf69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Package, class and interface descriptions</value>
      <webElementGuid>255ee66e-2eeb-470c-b38b-062da6f03803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rightIframe</value>
      <webElementGuid>266e639c-071f-499e-a461-d459777eeca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;rightContainer&quot;]/iframe[@class=&quot;rightIframe&quot;]</value>
      <webElementGuid>dc024099-e778-4bbb-99ad-aafb87a88069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='classFrame']</value>
      <webElementGuid>6ff5ba89-d341-4b15-8139-3398d5487283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>680c116d-ab1c-43f8-ac5c-867948b15a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'overview-summary.html' and @name = 'classFrame' and @title = 'Package, class and interface descriptions']</value>
      <webElementGuid>22b2394b-da39-4ad7-831f-7474679ffe71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
