<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_org.openqa.selenium.devtools.idealized</name>
   <tag></tag>
   <elementGuidId>a7a83211-fd25-4c3e-992a-d9a3a508091c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='i10']/th</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i10 > th.colFirst</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>996036d7-1a3d-4ba7-b695-361e72902796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>colFirst</value>
      <webElementGuid>c9c20171-d220-4a23-8356-4b77505f806b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>f6c1f60c-5258-47fa-a18f-076ce3ef4bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium.devtools.idealized</value>
      <webElementGuid>e4abfaf7-4849-4009-96b1-3c6c87dc666a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i10&quot;)/th[@class=&quot;colFirst&quot;]</value>
      <webElementGuid>463175f3-a0d5-4135-804a-c3c14ee6cf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Overview/iframe_classFrame</value>
      <webElementGuid>7cf1697f-e733-4249-9240-f3cb9103f7be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='i10']/th</value>
      <webElementGuid>f99a3995-d4bb-4826-b3b5-2de10fb060b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.devtools.events'])[1]/following::th[1]</value>
      <webElementGuid>6b10dc45-5237-4ddb-8de7-9cb89ba7c675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.devtools'])[1]/following::th[2]</value>
      <webElementGuid>ea624a82-6aec-4649-b94d-53c1473eb89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.devtools.idealized.browser.model'])[1]/preceding::th[1]</value>
      <webElementGuid>0281a66b-202a-45a2-8bac-11661c5a9008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/th</value>
      <webElementGuid>c6612a54-5c92-4c68-8540-a65c63144c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'org.openqa.selenium.devtools.idealized' or . = 'org.openqa.selenium.devtools.idealized')]</value>
      <webElementGuid>c8c1ff76-430e-40a9-ab05-63863e503a56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
