<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_org.openqa.selenium.bidi.log</name>
   <tag></tag>
   <elementGuidId>acbaf99c-ee5b-4bdb-8275-37ed1e8ed081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='i3']/th</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i3 > th.colFirst</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>e58c48c2-8433-4a60-8172-5cf42e521d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>colFirst</value>
      <webElementGuid>ed0e51e7-465a-41ac-99e9-5a148db7dbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>714cee53-bcff-4090-9db8-13c7139fe13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium.bidi.log</value>
      <webElementGuid>13ef89d3-793b-4713-b101-947cc85174b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i3&quot;)/th[@class=&quot;colFirst&quot;]</value>
      <webElementGuid>d3449b0a-7964-4f90-afb0-3d833926d006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Overview/iframe_classFrame</value>
      <webElementGuid>62040d63-adaf-4a24-a97f-0efa81e878f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='i3']/th</value>
      <webElementGuid>58e48e32-3d9d-46ce-ba0f-33952d2e64cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.bidi.browsingcontext'])[1]/following::th[1]</value>
      <webElementGuid>e89008b3-d186-4f2a-97a6-30265e19042c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.bidi'])[1]/following::th[2]</value>
      <webElementGuid>733ecf87-6d2f-49b9-b5e8-d8b10de246cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.chrome'])[1]/preceding::th[1]</value>
      <webElementGuid>9220f3ef-41d3-4d48-b473-97fc9d1b99d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/th</value>
      <webElementGuid>05f80405-a331-4360-9a00-c56699ea91f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'org.openqa.selenium.bidi.log' or . = 'org.openqa.selenium.bidi.log')]</value>
      <webElementGuid>77c9b6be-e04a-40ba-857b-d3fe6f4c69f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
