<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_2022 Google LLC_video-stream html5-ma_20cfc4</name>
   <tag></tag>
   <elementGuidId>ab950f16-a7c8-49b2-99d7-065692ed794e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div/video</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>video.video-stream.html5-main-video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>f9ebda7c-a744-495d-8727-0e62c116712b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>616dedca-f576-4194-8524-01187ccc6c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>video-stream html5-main-video</value>
      <webElementGuid>0f806a7a-2a8f-400f-bc2a-175aedbc56fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controlslist</name>
      <type>Main</type>
      <value>nodownload</value>
      <webElementGuid>18a2344e-13fe-4d97-9fd0-d7cbfa2cf731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://www.youtube.com/a8517c69-e10b-4b23-8ad2-9c04fd968b2d</value>
      <webElementGuid>bf5d7c37-e01a-4e68-a193-554d35cdc154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;html5-video-container&quot;]/video[@class=&quot;video-stream html5-main-video&quot;]</value>
      <webElementGuid>86ab0990-8630-4313-b833-9a47b29fa981</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div/video</value>
      <webElementGuid>85bc7262-6ebe-4820-b595-f33e06aaac53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>5a64756c-e7b0-43b6-ab22-ad949e33a8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'blob:https://www.youtube.com/a8517c69-e10b-4b23-8ad2-9c04fd968b2d']</value>
      <webElementGuid>b73e3d3a-6ab6-4cd2-83e5-49ac45e9d52a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
