<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Add Content_rdWindow_1</name>
   <tag></tag>
   <elementGuidId>5e3d0bb6-5c9d-4323-8a72-7435a72c8acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='rdWindow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;rdWindow&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ad19453d-fea9-47d8-abee-78fbb6ab3a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rdWindow</value>
      <webElementGuid>ff5805d0-1a94-4ad4-87c9-03ad9ddb32cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Collaboration/Hub/DialogHubContentInfo.aspx?GroupID=1&amp;ParentID=0&amp;ContentID=undefined&amp;sectionID=1&amp;objectID=59&amp;keyID=0&amp;onOpen=undefined&amp;ContentTypeId=1&amp;rwndrnd=0.31287910498076954</value>
      <webElementGuid>72eb6536-c76a-4934-a8a6-c330946a7324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46b43433-6f2e-4b93-b4f5-2585fb45be99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_rdWindow_C&quot;)/iframe[1]</value>
      <webElementGuid>4fb219f3-8667-4716-a259-30d41906defd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='rdWindow']</value>
      <webElementGuid>042c4ad7-c449-4dfc-b432-c8cec9fbbc89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_rdWindow_C']/iframe</value>
      <webElementGuid>174d4a64-2c2d-409e-a148-3f707d07308b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5434ff25-0e92-498b-b1e6-d69d268fbf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'rdWindow' and @src = '/Collaboration/Hub/DialogHubContentInfo.aspx?GroupID=1&amp;ParentID=0&amp;ContentID=undefined&amp;sectionID=1&amp;objectID=59&amp;keyID=0&amp;onOpen=undefined&amp;ContentTypeId=1&amp;rwndrnd=0.31287910498076954']</value>
      <webElementGuid>c8a652a0-50ad-4ccc-adc1-66b778784961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
