<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Add Content_rdWindow</name>
   <tag></tag>
   <elementGuidId>31913e4d-d0db-4889-96f7-8b4b7a0a4439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='rdWindow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;rdWindow&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e47860f5-65ee-40d3-9e7f-a0ec4a015904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rdWindow</value>
      <webElementGuid>c5381bb4-ec4c-4e02-b866-b5d9a12bd2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Collaboration/Hub/DialogHubContentInfo.aspx?GroupID=1&amp;ParentID=0&amp;ContentID=undefined&amp;sectionID=1&amp;objectID=59&amp;keyID=0&amp;onOpen=undefined&amp;ContentTypeId=1&amp;rwndrnd=0.9264172144782044</value>
      <webElementGuid>863163d5-c841-4ddb-a10f-311e2b020ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ba15f892-a4f5-46dd-877f-dfd557d192cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_rdWindow_C&quot;)/iframe[1]</value>
      <webElementGuid>585ce2de-e436-49b1-9a9d-138681c09827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='rdWindow']</value>
      <webElementGuid>52531bb6-f71d-4617-ad3f-34b79f90f6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_rdWindow_C']/iframe</value>
      <webElementGuid>6beca7ba-747f-4573-b7f2-4e46acd5b082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a4fe8ca8-1a28-4220-b5b3-7dc503d9eb71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'rdWindow' and @src = '/Collaboration/Hub/DialogHubContentInfo.aspx?GroupID=1&amp;ParentID=0&amp;ContentID=undefined&amp;sectionID=1&amp;objectID=59&amp;keyID=0&amp;onOpen=undefined&amp;ContentTypeId=1&amp;rwndrnd=0.9264172144782044']</value>
      <webElementGuid>d9f694cf-fae1-43c0-a8ae-6cdae8ea7431</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
