<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Post65_ctl00ctl00mainContentContentPl_e8e66d</name>
   <tag></tag>
   <elementGuidId>7f877a5d-b456-4ab7-adae-ca06c7765c58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd693182-4d81-4458-966f-fe3b3ecfe9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt</value>
      <webElementGuid>dc45813a-8964-4218-9fa5-774e48d25f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$ContentPlaceHolder1$ctl00$ctl00$dlCustomFields$ctl01$txtInt</value>
      <webElementGuid>ee427472-cd02-481d-b3d6-bc9a802816e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>riTextBox riFocused form-control invalid-control riHover form-control</value>
      <webElementGuid>858c8d40-fc0e-462b-8631-0085bb06e767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1f26744-409e-4b4e-8f4c-e3df0330bc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt&quot;)</value>
      <webElementGuid>6bfaaa8e-67e3-4d00-8666-2a09edb3cb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Hub/iframe_Add Content_rdWindow</value>
      <webElementGuid>ce7c834d-49dc-4515-a7db-0cef2939cbf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt']</value>
      <webElementGuid>fe43da5a-d940-47fe-a8de-00a6a9c7d664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt_wrapper']/input</value>
      <webElementGuid>9cc8edf1-2836-488f-af9c-c53696bd3be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>54710e9b-48a0-4592-afd3-1e5754fa2828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt' and @name = 'ctl00$ctl00$mainContent$ContentPlaceHolder1$ctl00$ctl00$dlCustomFields$ctl01$txtInt' and @type = 'text']</value>
      <webElementGuid>090fc4c0-f2e1-4b7e-858f-9c9e5039be3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
