<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_select_ctl00ctl00mainContentContentPl_fc3215 (1)</name>
   <tag></tag>
   <elementGuidId>40d19272-af10-4dcc-bc71-f504bf609690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f920fc7-e2aa-4bd3-ad58-d8707c859753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rbDecorated</value>
      <webElementGuid>cc2b4400-6ca5-4a88-b540-5d122a49fceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b05e6ab6-00ca-4493-ab30-77d2b3f87678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$ContentPlaceHolder1$btnSaveClose_input</value>
      <webElementGuid>bbf4be8a-1651-40be-930f-d33b8254e23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input</value>
      <webElementGuid>48b40e07-b48f-4ec3-9c5c-a00c8eb8a434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save &amp; Close</value>
      <webElementGuid>2dd3b995-e1f3-4d33-9025-6a6e882f5d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1425013b-7ed0-4d3d-8db0-e2e6f282861f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input&quot;)</value>
      <webElementGuid>e458c54b-0698-4141-a93d-4039e625ce0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Hub/iframe_Add Content_rdWindow_1</value>
      <webElementGuid>b4b55d1b-d7c7-48f6-b232-c41793f641e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input']</value>
      <webElementGuid>54738041-62a8-4c73-a661-37309f7ffa94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose']/input</value>
      <webElementGuid>537077e6-8376-4c24-ac41-3ac8d7f8b288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>3048690d-50f5-4c1a-a7a8-189756680f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'ctl00$ctl00$mainContent$ContentPlaceHolder1$btnSaveClose_input' and @id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input']</value>
      <webElementGuid>479e1483-dd12-48df-8d17-3c29d802a246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
