<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_select_ctl00ctl00mainContentContentPl_fc3215</name>
   <tag></tag>
   <elementGuidId>50071410-db10-4cda-9a20-06db115fe868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8aeeaf4b-ba9b-4daf-8bfe-76657d2145a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rbDecorated</value>
      <webElementGuid>0e47b3fb-d11e-491f-802b-2918fd301c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a94c64f-518a-4c2b-96ac-c6bbae56d1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$ContentPlaceHolder1$btnSaveClose_input</value>
      <webElementGuid>fdac2646-98bc-441b-bfae-62174400472c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input</value>
      <webElementGuid>aa1639c0-5e15-4314-a278-640ae7cc61ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save &amp; Close</value>
      <webElementGuid>e7410687-4026-41c2-8e4b-9c122ab0382f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4c21b95a-8aa8-4783-bd32-f7dfb6965414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input&quot;)</value>
      <webElementGuid>068e662d-2259-403b-8898-8e0068650e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Hub/iframe_Add Content_rdWindow</value>
      <webElementGuid>bc56a724-9ba5-4687-a4d8-0c0205f73e13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input']</value>
      <webElementGuid>3a9682bd-6bb5-4c50-945b-f012500a2fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose']/input</value>
      <webElementGuid>6b4f1460-156c-42c5-a136-ccb356e6d1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>5c33f317-d3fe-4e36-9e56-e2e6132404b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'ctl00$ctl00$mainContent$ContentPlaceHolder1$btnSaveClose_input' and @id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_btnSaveClose_input']</value>
      <webElementGuid>d6b408a6-0da3-4aeb-b701-077bdf091af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
