<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Post65_ctl00ctl00mainContentContentPl_e8e66d (1)</name>
   <tag></tag>
   <elementGuidId>420573b3-120a-40b1-abe1-073e773b29d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26992068-3d42-47f1-9034-8b216d5fce16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt</value>
      <webElementGuid>27b86449-05dd-496e-abbb-196835bc78f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$ContentPlaceHolder1$ctl00$ctl00$dlCustomFields$ctl01$txtInt</value>
      <webElementGuid>f48cbf99-10da-4d42-bd1e-4bfae743feac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>riTextBox riFocused form-control riHover form-control</value>
      <webElementGuid>00401b29-dc30-4d50-8147-1df33928d918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0cb0c76d-1c45-4e14-b624-6b481bce2d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt&quot;)</value>
      <webElementGuid>c204e8b6-3b40-46e9-957d-0afec40659cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Hub/iframe_Add Content_rdWindow_1</value>
      <webElementGuid>6b8d0ca8-31e2-49a5-8922-38bbe50adf82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt']</value>
      <webElementGuid>99ce776b-c925-48cb-9b77-2da5737add96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt_wrapper']/input</value>
      <webElementGuid>ec3a8685-4078-4f26-98ad-9334c8d6043b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>e22f9c81-face-425c-bce1-77cf0562fcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_dlCustomFields_ctl01_txtInt' and @name = 'ctl00$ctl00$mainContent$ContentPlaceHolder1$ctl00$ctl00$dlCustomFields$ctl01$txtInt' and @type = 'text']</value>
      <webElementGuid>e94f6827-bf72-4b8a-a7d2-53e3cfc036bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
