<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_General Information_caret</name>
   <tag></tag>
   <elementGuidId>b78a5247-826b-4acd-beb1-d9280925a499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='add-content-dropdown']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-content-dropdown > span.caret</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>267df3f9-b304-486c-b6e0-9a806b724340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
      <webElementGuid>1dd0b561-2170-43d6-9184-c49c1e1028d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-content-dropdown&quot;)/span[@class=&quot;caret&quot;]</value>
      <webElementGuid>598c9800-8e99-42ff-857c-e01dbab823a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='add-content-dropdown']/span</value>
      <webElementGuid>a384ce0e-7db4-4eef-b4d5-93c2bfc5388e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a/span</value>
      <webElementGuid>1bd603b5-1391-46b5-b7c0-942e6e24861a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
